<?php
$result = array(
    array(
        "estate_type" => "기타",
        "exchange_fg" => "N",
        "max_area" => 2402,
        "max_price" => 3619,
        "min_area" => 2318,
        "min_price" => 1532,
        "noti_count" => 1,
        "phone" => "01030242152",
        "public_fg" => "N",
        "reg_date" => "2024-06-12",
        "sale_type" => "매매",
        "sgg" => "수원시 장안구",
        "sgg_cd" => "111",
        "sido" => "경기도",
        "sido_cd" => "41",
        "view_count" => 2,
        "wanted_no" => 499,
    ),
    array(
        "estate_type" => "기타",
        "exchange_fg" => "N",
        "max_area" => 2402,
        "max_price" => 3619,
        "min_area" => 2318,
        "min_price" => 1532,
        "noti_count" => 1,
        "phone" => "01030242152",
        "public_fg" => "N",
        "reg_date" => "2024-06-12",
        "sale_type" => "매매",
        "sgg" => "수원시 장안구",
        "sgg_cd" => "111",
        "sido" => "경기도",
        "sido_cd" => "41",
        "view_count" => 2,
        "wanted_no" => 499,
    ),
    array(
        "estate_type" => "기타",
        "exchange_fg" => "N",
        "max_area" => 2402,
        "max_price" => 3619,
        "min_area" => 2318,
        "min_price" => 1532,
        "noti_count" => 1,
        "phone" => "01030242152",
        "public_fg" => "N",
        "reg_date" => "2024-06-12",
        "sale_type" => "매매",
        "sgg" => "수원시 장안구",
        "sgg_cd" => "111",
        "sido" => "경기도",
        "sido_cd" => "41",
        "view_count" => 2,
        "wanted_no" => 499,
    ),
    array(
        "estate_type" => "기타",
        "exchange_fg" => "N",
        "max_area" => 2402,
        "max_price" => 3619,
        "min_area" => 2318,
        "min_price" => 1532,
        "noti_count" => 1,
        "phone" => "01030242152",
        "public_fg" => "N",
        "reg_date" => "2024-06-12",
        "sale_type" => "매매",
        "sgg" => "수원시 장안구",
        "sgg_cd" => "111",
        "sido" => "경기도",
        "sido_cd" => "41",
        "view_count" => 2,
        "wanted_no" => 499,
    ),
    array(
        "estate_type" => "기타",
        "exchange_fg" => "N",
        "max_area" => 2402,
        "max_price" => 3619,
        "min_area" => 2318,
        "min_price" => 1532,
        "noti_count" => 1,
        "phone" => "01030242152",
        "public_fg" => "N",
        "reg_date" => "2024-06-12",
        "sale_type" => "매매",
        "sgg" => "수원시 장안구",
        "sgg_cd" => "111",
        "sido" => "경기도",
        "sido_cd" => "41",
        "view_count" => 2,
        "wanted_no" => 499,
    )
);

echo json_encode($result); // 배열을 출력하여 확인