<?php
$result = array(
    array(
        "wanted_no" => "500",
        "sido_cd" => "26",
        "sgg_cd" => "170",
        "exchange_fg" => "N",
        "sale_price" => "77396",
        "rent_price" => "14",
        "area" => "2851",
        "phone" => "01044903613",
        "noti_count" => "0",
        "view_count" => "0",
        "public_fg" => "N",
        "reg_date" => "2024-06-17",
        "estate_type" => "오피스텔",
        "sale_type" => "임대",
        "sido" => "부산광역시",
        "sgg" => "동구",
    ),
    array(
        "wanted_no" => "500",
        "sido_cd" => "26",
        "sgg_cd" => "170",
        "exchange_fg" => "N",
        "sale_price" => "77396",
        "rent_price" => "14",
        "area" => "2851",
        "phone" => "01044903613",
        "noti_count" => "0",
        "view_count" => "0",
        "public_fg" => "N",
        "reg_date" => "2024-06-17",
        "estate_type" => "오피스텔",
        "sale_type" => "임대",
        "sido" => "부산광역시",
        "sgg" => "동구",
    ),
    array(
        "wanted_no" => "500",
        "sido_cd" => "26",
        "sgg_cd" => "170",
        "exchange_fg" => "N",
        "sale_price" => "77396",
        "rent_price" => "14",
        "area" => "2851",
        "phone" => "01044903613",
        "noti_count" => "0",
        "view_count" => "0",
        "public_fg" => "N",
        "reg_date" => "2024-06-17",
        "estate_type" => "오피스텔",
        "sale_type" => "임대",
        "sido" => "부산광역시",
        "sgg" => "동구",
    ),
    array(
        "wanted_no" => "500",
        "sido_cd" => "26",
        "sgg_cd" => "170",
        "exchange_fg" => "N",
        "sale_price" => "77396",
        "rent_price" => "14",
        "area" => "2851",
        "phone" => "01044903613",
        "noti_count" => "0",
        "view_count" => "0",
        "public_fg" => "N",
        "reg_date" => "2024-06-17",
        "estate_type" => "오피스텔",
        "sale_type" => "임대",
        "sido" => "부산광역시",
        "sgg" => "동구",
    ),
    array(
        "wanted_no" => "500",
        "sido_cd" => "26",
        "sgg_cd" => "170",
        "exchange_fg" => "N",
        "sale_price" => "77396",
        "rent_price" => "14",
        "area" => "2851",
        "phone" => "01044903613",
        "noti_count" => "0",
        "view_count" => "0",
        "public_fg" => "N",
        "reg_date" => "2024-06-17",
        "estate_type" => "오피스텔",
        "sale_type" => "임대",
        "sido" => "부산광역시",
        "sgg" => "동구",
    )
);

echo json_encode($result); // 배열을 출력하여 확인